# Project 4: Sequential Structure from Motion

### Due 4/3/2019

### Graduate Students: Our next reading is [Snavely, 2006](http://195.130.87.21:8080/dspace/bitstream/123456789/636/1/Photo%20tourism%20exploring%20photo%20collections%20in%203D.pdf).  We'll have a written report on this one: these methods papers aren't as good for discussions as I'd hoped.

## Problem Statement

You have now developed code that takes two photographs, finds matching locations in both, determines the relative motion between the cameras that took both photos, and solves for the 3D position of those points using epipolar geometry.  **The next (and final for our purposes) stage is to extend this analysis to more than two images**, such that we can build 3D models of objects on the ground with just about as much detail as we'd like.

## Adding the third photo
How do we add these additional photos?  To be perfectly honest, at this point it's mostly an exercise in match housekeeping: we've already developed most of the code that we need.  First, let's consider what we've got after matching our first two images, $I_1$ and $I_2$.  First, we have a set of keypoints in each image, associated with a set of matches.  These matches have been quality controlled twice:  first by the ratio test, then by RANSAC in conjunction with the recovery of the essential matrix.  Assuming that we've used our known camera matrix to convert our pixel-wise coordinates to generalized coordinates, let's call these keypoints $\mathbf{x}_1$ and $\mathbf{x}_2$.  In practice, we can drop all of those keypoints for which there is not an associated accepted match.  Then, for each of our kept matches, we have the essential matrix $E_{12}$, from which we can extract a pair of projection matrices $\mathbf{P}_1 = [\mathbf{I}|\mathbf{0}]$ and $\mathbf{P}_2 = [\mathbf{R}_2|\mathbf{t}_2]$.  Using these projection matrices, we generated 3D, world coordinate location of the corresponding features that showed up robustly in both images.  We'll call these coordinates $\mathbf{X}_{12}$.  

To add a third image $\mathbf{I}_3$ to the mix, consider that the situation outlined above is sort of analogous to the information that we have when we want to do pose estimation with ground control points: we have 3D world coordinates as well as the image coordinates of a set of points (a bunch of them, usually!), and we want to recover the camera pose.  The problem is that the feature generalized coordinates that we've computed are for $I_1$ and $I_2$, but not $I_3$.  Is this a big problem?  Of course not!  We can simply find $\mathbf{x}_3$ in $I_3$ that correspond to $\mathbf{x}_2$, the keypoints in the second image.  Then we identify these keypoints with the 3D poi nts $\mathbf{X}_{12}$.  Thus we have image coordinates of features in the third image and the corresponding world coordinates: we can now perform pose estimation, just as we did in Project 1.  

Of course there are a few minor caveats: first, we need to filter out spurious matches between $\mathbf{x}_2$ and $\mathbf{x}_3$.  To do this, we can utilize a tool that we already have: RANSAC estimation of the essential matrix.  Because $I_2$ and $I_3$ are related by epipolar geometry just as $I_1$ and $I_2$ are, we can use the same subroutine to compute the essential matrix $\mathbf{E}_{23}$, and (critically) identify and filter outliers, i.e. we'll discard matches that don't don't correspond to the consensus view of the essential matrix.  This also leads to the next caveat, namely that we need an initial guess (call it $P_3^0$) for pose estimation to converge properly.  Where should this initial guess come from?  The $\mathbf{E}_{23}$ provides a rotation given as if camera 2 were canonical, i.e. $\mathbf{P_2'}=[\mathbf{I}|\mathbf{0}]$, $\mathbf{P_3}'=[\mathbf{R}_3'|\mathbf{t}_3']$.  We'll call it $P_3'$.  We need to convert this projection matrix to a coordinate system in which $I_1$ (not $I_2$) is canonical.  Fortunately, this is easy:
$$
P_3 \approx P_2 P_3'.
$$
This $P_3$, is a an excellent initial guess for pose estimation (in principle, it's rotation matrix should actually be correct).  Note that the translation component is only good up to a constant: however, this isn't too problematic because its direction is close to correct, and any optimization just needs to perform what amounts to a line search (a univariate optimization problem) to find the correct scaling. 

Once we have a robust estimation of the third camera's pose, we can use it do point triangulation on the correspondences between $I_2$ and $I_3$ not associated with an already-known world coordinate point, which allows us to augment our 3D model with new points.  Additionally, we can perform triangulation with *3 views*, potentially improving our accuracy.  Moreover, we can apply the process above iteratively, adding more and more images to generate a highly featured 3D model from (for example) 360 degrees worth of view angles.  

## Application
**Generate code that performs the above process for a third image.  Apply it to one of the 3D image datasets that we generated in class.  Note that we will be collecting aerial imagery from drones as well.  Apply this method to a sequence of drone imagery as well.**  As a challenge, can you implement code that sequentially adds an arbitrary number of images?


In [51]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
import piexif
import scipy.optimize as so

def get_best_sift_matches(I_1, I_2, r=0.7):

    sift = cv2.xfeatures2d.SIFT_create(contrastThreshold=0.04, edgeThreshold=10, sigma=1.6)
    kp1, des1 = sift.detectAndCompute(I_1, None)
    kp2, des2 = sift.detectAndCompute(I_2, None)

    matcher = cv2.BFMatcher()
    matches = matcher.knnMatch(des1, des2, k=2)

    good_matches = []
    for m, n in matches:
        # Compute the ratio between best match m, and second best match n here
        if m.distance < r * n.distance:
            good_matches.append(m)

    u1 = []
    u2 = []

    for g in good_matches:
        u1.append(kp1[g.queryIdx].pt)
        u2.append(kp2[g.trainIdx].pt)

    u1 = np.array(u1)
    u2 = np.array(u2)

    u1 = np.c_[u1, np.ones(u1.shape[0])]
    u2 = np.c_[u2, np.ones(u2.shape[0])]

    return u1, u2

In [59]:
def get_correspondence_points(I_1, img_name, u1, u2):
    h,w,d = I_1.shape
    exif = piexif.load(img_name)
    f = exif['Exif'][piexif.ExifIFD.FocalLengthIn35mmFilm]/36*w
    cu = w//2
    cv = h//2

    K_cam = np.array([[f,0,cu], [0,f,cv], [0,0,1]])
    K_inv = np.linalg.inv(K_cam)
    x1 = u1 @ K_inv.T
    x2 = u2 @ K_inv.T 
    
    # compute E and inliers
    E, inliers = cv2.findEssentialMat(x1[:, :2], x2[:, :2], np.eye(3), method=cv2.RANSAC, threshold=1e-3)
    inliers = inliers.ravel().astype(bool)
    
    # recover pose
    n_in, R, t,_ = cv2.recoverPose(E, x1[inliers,:2], x2[inliers,:2])

    # compute camera matrices
    P_1 = np.array([[1,0,0,0],
                [0,1,0,0],
                [0,0,1,0]])
    P_2 = np.hstack((R, t))
    
    # convert image to camera coordinates
    P_1c = K_cam @ P_1
    P_2c = K_cam @ P_2
        
    # triangulate using linear solution for each point in x1, and x2
    point_cloud = []
    for a,b in zip(x1[inliers,:], x2[inliers,:]):
        t_point = triangulate(P_1c, P_2c, a, b)
        t_point /= t_point[-1] 
        point_cloud.append(t_point[:3])
        
    return point_cloud, P_1, P_2, P_1c, P_2c, x1[inliers, :], x2[inliers, :], inliers

In [60]:
def triangulate(P0,P1,x1,x2):
    # P0,P1: projection matrices for each of two cameras/images
    # x1,x1: corresponding points in each of two images (If using P that has been scaled by K, then use camera
    # coordinates, otherwise use generalized coordinates)
    A = np.array([[P0[2,0]*x1[0] - P0[0,0], P0[2,1]*x1[0] - P0[0,1], P0[2,2]*x1[0] - P0[0,2], P0[2,3]*x1[0] - P0[0,3]],
                  [P0[2,0]*x1[1] - P0[1,0], P0[2,1]*x1[1] - P0[1,1], P0[2,2]*x1[1] - P0[1,2], P0[2,3]*x1[1] - P0[1,3]],
                  [P1[2,0]*x2[0] - P1[0,0], P1[2,1]*x2[0] - P1[0,1], P1[2,2]*x2[0] - P1[0,2], P1[2,3]*x2[0] - P1[0,3]],
                  [P1[2,0]*x2[1] - P1[1,0], P1[2,1]*x2[1] - P1[1,1], P1[2,2]*x2[1] - P1[1,2], P1[2,3]*x2[1] - P1[1,3]]])
    u,s,vt = np.linalg.svd(A)
    return vt[-1]

In [61]:
class Camera(object):
    def __init__(self):
        self.p = None                   # Pose
        self.f = None                   # Focal Length in Pixels
        self.c = np.array([None,None])  # Sensor
        
    def projective_transform(self,x):
        """  
        This function performs the projective transform on generalized coordinates in the camera reference frame.
        """
        focal = self.f
        sensor = self.c
        
        #General Coordinates
        gcx = x[0]/x[2]
        gcy = x[1]/x[2]
        
        #Pixel Locations
        pu = gcx*focal + sensor[0]/2.
        pv = gcy*focal + sensor[1]/2.
        
        return np.array([pu,pv])
      
    
    def rotational_transform(self,X,pts):
        """  
        This function performs the translation and rotation from world coordinates into generalized camera coordinates.
        """
        
        cam_x = X[0]
        cam_y = X[1]
        cam_z = X[2]
        roll = X[3]
        pitch = X[4]
        yaw = X[5]
        
        r_axis = np.array([[1, 0, 0], [0, 0,-1], [0, 1, 0]])
        r_roll = np.array([[np.cos(roll), 0, -1*np.sin(roll)], [0, 1, 0], [np.sin(roll), 0, np.cos(roll)]])
        r_pitch = np.array([[1, 0, 0], [0, np.cos(pitch), np.sin(pitch)], [0, -1*np.sin(pitch), np.cos(pitch)]])
        r_yaw = np.array([[np.cos(yaw), -1*np.sin(yaw), 0, 0], [np.sin(yaw), np.cos(yaw), 0, 0], [0, 0, 1, 0]])

        T = np.array([[1, 0, 0, -cam_x],[0, 1, 0, -cam_y], [0, 0, 1, -cam_z], [0, 0, 0, 1]])
        
        C = r_axis @ r_roll @ r_pitch @ r_yaw @ T

        return C @ pts
    
    def rotational_transform_x(self, X):
        """
        This function performs the translation and rotation from world coordinates into generalized camera coordinates.
        """

        # Unpack pose? could do something different here.
        X_cam, Y_cam, Z_cam, azimuth_cam_deg, pitch_cam_deg, roll_cam_deg = self.p

        # Make X a set of homogeneous coors
        X = np.vstack((X, np.ones(X.shape[1])))

        # Convert degrees to radians
        azimuth_cam_rad = np.deg2rad(azimuth_cam_deg)
        pitch_cam_rad = np.deg2rad(pitch_cam_deg)
        roll_cam_rad = np.deg2rad(roll_cam_deg)

        translation_vec = [X_cam, Y_cam, Z_cam]
        C = self.make_cam_mtx(azimuth_cam_rad, pitch_cam_rad, roll_cam_rad, translation_vec)

        return C @ X
    
    def estimate_pose(self,gcps):
        """
        This function adjusts the pose vector such that the difference between the observed pixel coordinates u_gcp 
        and the projected pixels coordinates of X_gcp is minimized.
        """
        p_opts = [] # Initial easting, northing, elevation positions
        u_gcps = [] # Initial projected u,v coordinates

        for gcp in gcps:
            pts = gcp[2:5]
            # Add homogenous coordinate
            pts= np.append(pts, 1)

            # Observed pixel coordinates
            u_gcp = gcp[0:2]
            p_opts.append(pts)
            u_gcps.append(u_gcp)
    
        ave_easting = np.mean([gcp[2] for gcp in gcps])
        ave_northing = np.mean([gcp[3] for gcp in gcps])
        ave_elevation = np.mean([gcp[4] for gcp in gcps])
            
        # Initial guess at the pose
        p0 = np.array([ave_easting, ave_northing, ave_elevation,90,45,45])
        
        # print(p0, '\n', p_opts, '\n', u_gcps, '\n')
        
        # Find the optimal pose minimizing the residual
        p_opt = so.least_squares(self.residual, p0, method='lm', args=(p_opts,u_gcps))['x']
        
        self.p = p_opt
        
    # Function to transform all gcps into the camera coordinates
    def transform_all(self, X_gcp, p):
        transformed = []
        
        for gcp in X_gcp:
            # Perform rotational transform on X_gcp
            rotated = self.rotational_transform(p, gcp)
            
            # Project the rotated coordinates to pixel coordinates
            projected = self.projective_transform(rotated)
            transformed.append(projected)

        return transformed
    
    # Calculate the difference in the estimate projection of X_gcp and actual positions of u_gcp
    def residual(self, p0, X_gcp, u_gcp):
        all_res = np.array(self.transform_all(X_gcp, p0)) - np.array(u_gcp)
        all_res = all_res.ravel()
        
        return all_res

In [62]:
img1 = plt.imread("./pictures/cube/DSC03896.JPG")
img2 = plt.imread("./pictures/cube/DSC03897.JPG")
img3 = plt.imread("./pictures/cube/DSC03898.JPG")

u11, u21 = get_best_sift_matches(img1, img2, r=0.7)
X12, P_1, P_2, P_1c, P_2c, x1, x2, in12 = get_correspondence_points(img1, "./pictures/cube/DSC03896.JPG", u11, u21)
    
u22, u31 = get_best_sift_matches(img2, img3, r=0.7)
X23, P_2p, P_3p, P_2pc, P_3pc, x2_p, x3, in23 = get_correspondence_points(img2, "./pictures/cube/DSC03897.JPG", u22, u31)

P_2 = np.vstack((P_2, [0, 0, 0, 1]))
P_3p = np.vstack((P_3p, [0, 0, 0, 1]))

P_3 = P_2 @ P_3p

P_3 = P_3[:3, :]

print(P_3)

[[ 0.48485876 -0.73058377  0.48079032 -1.67283012]
 [ 0.73282444  0.63942302  0.23260811 -0.85833798]
 [-0.47736811  0.23955282  0.8454195   0.56530148]]


In [63]:
print(len(x1), len(x2), len(x2_p), len(x3), len(X12), len(X23))

uv_3 = x3
ene_3 = X23

uv_3 = np.array(uv_3)[:, :2]
ene_3 = np.array(ene_3)

gcps_3 = np.hstack((uv_3, ene_3))

print('\n', gcps_3, '\n\n', 'Length:', len(gcps_3))

462 462 605 605 462 605

 [[-0.28042791 -0.06006592 -0.95351062 -0.43556498  2.94391192]
 [-0.28022785 -0.05987755 -0.95351024 -0.43556488  2.94391153]
 [-0.28022785 -0.05987755 -0.95351024 -0.43556488  2.94391153]
 ...
 [ 0.28712245  0.16470879 -0.95333654 -0.43557328  2.94400224]
 [ 0.31555187  0.12221343 -0.95334143 -0.43559039  2.94401676]
 [ 0.31805132  0.12342592 -0.95334085 -0.4355904   2.94401746]] 

 Length: 605


In [57]:
# # set of keypoints across all three images
# # from generalized coordinates x1:x2 and x2:x3, find shared matches
# h,w,d = img1.shape
# exif = piexif.load("./pictures/cube/DSC03896.JPG")
# f = exif['Exif'][piexif.ExifIFD.FocalLengthIn35mmFilm]/36*w
# cu = w//2
# cv = h//2

# K_cam = np.array([[f,0,cu], [0,f,cv], [0,0,1]])
# K_inv = np.linalg.inv(K_cam)
# x1 = u11 @ K_inv.T
# x21 = u21 @ K_inv.T

# h,w,d = img2.shape
# exif = piexif.load("./pictures/cube/DSC03897.JPG")
# f = exif['Exif'][piexif.ExifIFD.FocalLengthIn35mmFilm]/36*w
# cu = w//2
# cv = h//2

# K_cam = np.array([[f,0,cu], [0,f,cv], [0,0,1]])
# K_inv = np.linalg.inv(K_cam)
# x22 = u22 @ K_inv.T
# x3 = u31 @ K_inv.T            

In [64]:
cam3 = Camera()

h,w,d = img3.shape
cu = w//2
cv = h//2

exif = piexif.load("./pictures/cube/DSC03898.JPG")
f = exif['Exif'][piexif.ExifIFD.FocalLengthIn35mmFilm]/36*w
cam3.f = f
cam3.c = np.array([4032.,3024.]) # Sensor size

K_cam = np.array([[f,0,cu], [0,f,cv], [0,0,1]])
K_inv = np.linalg.inv(K_cam)

P_3c = K_cam @ P_3

cam3.estimate_pose(gcps_3)

print("Easting: ", cam3.p[0])
print("Northing: ", cam3.p[1])
print("Elevation: ", cam3.p[2])
print("Roll: ", cam3.p[3])
print("Pitch: ", cam3.p[4])
print("Yaw: ", cam3.p[5])

Easting:  -0.9534031528468377
Northing:  -0.4355359559494288
Elevation:  2.9439100243327325
Roll:  90.00027590400317
Pitch:  44.995066824243345
Yaw:  44.986708582422075


In [67]:
print(in12, '\n', in23)

# Find the points in 3 that do not correspond
# with a match in 1 and 2 to add to the point_cloud

point_cloud = X12


# # For every inlier point in 3 from the 2 and 3 match
# for a in range(len(x3)):
#     in_match12 = False
    
#     # Check for the existence of the correspondence
#     # point in 1 and 2's match
    

[ True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False  True False False False False
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False False  True  True  True
  True False  True  True  True False False False  True  True  True False
 False False  True False  True  True False  True  True  True  True  True
  True  True False  True False  True  True  True  True  True  True False
 False  True  True  True  True False False  True  True False  True  True
 False  True  True  True  True  True  True  True  True  True False  True
  True False  True False False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T